@echo off
echo Dang tat tat ca Python processes...
taskkill /F /IM python.exe 2>nul
echo Cho 3 giay...
timeout /t 3 /nobreak >nul
echo Bat dau chay bot...
python telegram_coin_tracker_bot.py
pause
